apiVersion: v2
name: InterneTaakAfhandeling
description: Umbrella chart for InterneTaakAfhandeling including Web API and Poller
type: application
version: 3.0.5
dependencies:
  - name: InterneTaakAfhandeling-Web
    version: 0.1.6
    repository: file://charts/InterneTaakAfhandeling-Web-chart
  - name: InterneTaakAfhandeling-Poller
    version: 0.2.2
    repository: file://charts/InterneTaakAfhandeling-Poller-chart
