apiVersion: v2
name: internetaakafhandeling
description: Umbrella chart for InterneTaakAfhandeling including Web API and Poller
type: application
version: 0.0.8
dependencies:
  - name: internetaakafhandeling-web
    version: 0.0.8
    repository: file://charts/internetaakafhandeling-web-chart
  - name: internetaakafhandeling-poller
    version: 0.0.8
    repository: file://charts/internetaakafhandeling-poller-chart
