apiVersion: v2
name: InterneTaakAfhandeling
description: Umbrella chart for InterneTaakAfhandeling including Web API and Poller
type: application
version: 0.0.1
dependencies:
  - name: InterneTaakAfhandeling-Web
    version: 0.0.1
    repository: file://charts/internetaakafhandeling-web-chart
  - name: InterneTaakAfhandeling-Poller
    version: 0.0.1
    repository: file://charts/internetaakafhandeling-poller-chart
