ingress:
  enabled: true
  host: ita.test.icatt.nl
  port: 80

certificates:
  enabled: true
  installClusterIssuer: true      # true for non-local clusters
  issuerName: "letsencrypt-prod"  # use "letsencrypt-prod" in staging/production and "selfsigned-issuer" for local
  commonName: ita.test.icatt.nl
  email: placeholder@placeholder.nl

service:
  type: LoadBalancer

# PostgreSQL configuration for superuser
global:
  postgresql:
    auth:
      postgresPassword: "placeholder"

# PostgreSQL configuration
postgresql:
  enabled: true
  auth:
    username: placeholder
    password: placeholder
    database: placeholder
  primary:
    persistence:
      enabled: true
      size: 8Gi
  metrics:
    enabled: false

# Shared configuration
config:
  pollerMessage: "Poller uitgevoerd om:"
  openKlantApi:
    baseUrl: "https://placeholder.placeholder.nl/placeholder/api/v1/"
  objectApi:
    baseUrl: "https://placeholder.placeholder.nl/api/v2/"
  database:
    # When postgresql.enabled=true, host is auto-set to {Release.Name}-postgresql
    # Specify this host only when postgresql.enabled=false
    host: ""  
    # These values are used regardless of postgresql.enabled setting
    port: "5432"
    name: "placeholder"
    username: "placeholder"
  zaakSysteem:
    baseUrl: "https://placeholder.placeholder.nl/"
    clientId: "placeholder"

# Shared secrets
secrets:
  objectApiKey: "placeholder"
  openKlantApiKey: "placeholder"
  databasePassword: "placeholder"
  zaakSysteemKey: "placeholder"

internetaakafhandeling-web:
  image:
    repository: "ghcr.io/interne-taak-afhandeling/internetaakafhandeling.web"
    tag: "0.0.8-06ffa27" # deploy overwrites this tag automatically
    pullPolicy: Always
  config:
    setting1: "Umbrella chart setting1 value"
    setting2: "Umbrella chart setting2 value"
  # If you have any web-specific secrets, add them here
  secrets: {}
    
internetaakafhandeling-poller:
  schedule: "* * * * *"
  image:
    repository: "ghcr.io/interne-taak-afhandeling/internetaakafhandeling.poller"
    tag: "0.0.3-4a39096" # deploy overwrites this tag automatically
    pullPolicy: Always
  config:
    smtp:
      host: "placeholder.placeholder.nl"
      port: "2525"
      username: ""
      fromEmail: "placeholder@placeholder.nl"
      enableSsl: "true"
    internetakenNotifier:
      hourThreshold: "-10000"
  secrets:
    smtp:
      password: "" # value comes from secrets