ingress:
  enabled: true
  host: InterneTaakAfhandeling.local
  port: 80

certificates:
  enabled: true
  installClusterIssuer: false
  issuerName: "selfsigned-issuer"  # use "letsencrypt-prod" in staging/production
  commonName: InterneTaakAfhandeling.local
  email: pascal@icatt.nl

service:
  type: LoadBalancer

config:
  globalSetting: "shared-value"

secrets:
  apiKey: "shared-api-key"

InterneTaakAfhandeling-Web:
  image:
    repository: "ghcr.io/pascalicatt/InterneTaakAfhandeling.Web"
    tag: "0.0.1-546f239" # deploy overwrites this tag automatically
    pullPolicy: Always
  appsettings:
    setting1: "Umbrella chart setting1 value"
    setting2: "Umbrella chart setting2 value"
    
InterneTaakAfhandeling-Poller:
  image:
    repository: "ghcr.io/pascalicatt/InterneTaakAfhandeling.Poller"
    tag: "0.0.1-546f239" # deploy overwrites this tag automatically
    pullPolicy: Always
  appsettings:
    PollerMessage: "Umbrella chart value"