services:
  website:
    profiles:
      - web
    build:
      context: .
      dockerfile: InterneTaakAfhandeling.Web.Server/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - postgres
  postgres:
    image: postgres:17
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=InterneTaakAfhandeling
    volumes:
      - postgres-data:/var/lib/postgresql/data
  poller:
    profiles:
      - poller
    build:
      context: .
      dockerfile: InterneTaakAfhandeling.Poller/Dockerfile
    depends_on:
      - postgres

volumes:
  postgres-data: