services:
  website:
    build:
      context: .
      dockerfile: InterneTaakAfhandeling.Web.Server/Dockerfile
    ports:
      - 8080:8080
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=InterneTaakAfhandeling
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=InterneTaakAfhandeling
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
