services:
  website:
    image: internetaakafhandeling-web
    build:
      context: .
      dockerfile: InterneTaakAfhandeling.Web.Server/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - postgres
  
  postgres:
    image: postgres:17
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: InterneTaakAfhandeling
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
  
  poller:
    image: internetaakafhandeling-poller
    build:
      context: .
      dockerfile: InterneTaakAfhandeling.Poller/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres-data: