apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "InterneTaakAfhandeling.Poller.fullname" . }}-appsettings
data:
  appsettings.json: |-
    {
      "PollerMessage": "{{ .Values.appsettings.PollerMessage }}"
    }