apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "internetaakafhandeling.poller.fullname" . }}-appsettings
data:
  appsettings.json: |-
    {
      "PollerMessage": "{{ .Values.appsettings.PollerMessage }}",
      "OpenKlantApi": {
        "BaseUrl": "{{ .Values.appsettings.OpenKlantApi.BaseUrl }}",
        "ApiKey": "{{ .Values.appsettings.OpenKlantApi.ApiKey }}"
      }
    }
