apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "internetaakafhandeling.poller.fullname" . }}
spec:
  schedule: "{{ .Values.schedule }}"
  jobTemplate:
    spec:
      template:
      spec:
          containers:
            - name: internetaakafhandeling-poller
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              envFrom:
                # Mount shared config and secrets
                - configMapRef:
                    name: {{ include "internetaakafhandeling.fullname" . }}-shared-config
                - secretRef:
                    name: {{ include "internetaakafhandeling.fullname" . }}-shared-secret

                # Mount poller-specific config and secrets
                - configMapRef:
                    name: {{ include "internetaakafhandeling.poller.fullname" . }}-private-config
                - secretRef:
                    name: {{ include "internetaakafhandeling.poller.fullname" . }}-private-secret
          restartPolicy: OnFailure

          