apiVersion: v1
kind: Secret
metadata:
  name: {{ include "internetaakafhandeling.poller.fullname" . }}-private-secret
type: Opaque
data:
  password: {{ "internetaakafhandeling.poller-secret" | b64enc }}