apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "internetaakafhandeling.web.fullname" . }}-appsettings
data:
  appsettings.json: |-
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "AllowedHosts": "*",
      "Setting1": "{{ .Values.appsettings.setting1 }}",
      "Setting2": "{{ .Values.appsettings.setting2 }}"
    }