apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "InterneTaakAfhandeling.Web.fullname" . }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ include "InterneTaakAfhandeling.Web.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "InterneTaakAfhandeling.Web.name" . }}
    spec:
      containers:
        - name: InterneTaakAfhandeling-Web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          volumeMounts:
          - name: appsettings-volume
            mountPath: /app/appsettings.json
            subPath: appsettings.json
      volumes:
        - name: appsettings-volume
          configMap:
            name: {{ include "InterneTaakAfhandeling.Web.fullname" . }}-appsettings