apiVersion: v1
kind: Secret
metadata:
  name: {{ include "internetaakafhandeling.web.fullname" . }}-private-secret
type: Opaque
data:
  password: {{ "internetaakafhandeling.web-secret" | b64enc }}
  {{- if (.Values.config).oidc }}
  OIDC_CLIENT_SECRET: {{ .Values.config.oidc.clientSecret | b64enc }}
  {{- end }}

