apiVersion: v1
kind: Service
metadata:
  name: {{ include "InterneTaakAfhandeling.Web.fullname" . }}-svc
spec:
  type: ClusterIP
  selector:
    app: {{ include "InterneTaakAfhandeling.Web.name" . }}
  ports:
    - port: 80
      targetPort: 8080