apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "internetaakafhandeling.nieuweInternetaakNotificatie.name" . }}
  labels:
    {{- include "internetaakafhandeling.nieuweInternetaakNotificatie.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.nieuweInternetaakNotificatie.schedule }}"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "internetaakafhandeling.nieuweInternetaakNotificatie.selectorLabels" . | nindent 12 }}
        spec:
          containers:
            - name: nieuwe-internetaak-notificatie
              image: "{{ .Values.poller.image.repository }}:{{ .Values.poller.image.tag }}"
              imagePullPolicy: {{ .Values.poller.image.pullPolicy }}
              {{- with .Values.poller.resources }}
              resources:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              envFrom:
                - configMapRef:
                    name: {{ include "internetaakafhandeling.fullname" . }}-config
                - secretRef:
                    name: {{ include "internetaakafhandeling.fullname" . }}-secrets
          restartPolicy: OnFailure
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
