{{- if .Values.poller.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "internetaakafhandeling.poller.fullname" . }}-secret
  labels:
    {{- include "internetaakafhandeling.poller.labels" . | nindent 4 }}
type: Opaque
data:
  # Database connection
  ConnectionStrings__DefaultConnection: {{ include "internetaakafhandeling.poller.databaseConnectionString" . | b64enc }}
  
  # API Keys
  OpenKlantApi__ApiKey: {{ .Values.poller.apiConnections.openKlant.apiKey | b64enc }}
  ObjectApi__ApiKey: {{ .Values.poller.apiConnections.object.apiKey | b64enc }}
  ZaakSysteem__Key: {{ .Values.poller.apiConnections.zaakSysteem.key | b64enc }}
  
  # SMTP Password
  Email__SmtpSettings__Password: {{ .Values.poller.smtp.password | b64enc }}
{{- end }}