apiVersion: v1
kind: Secret
metadata:
  name: {{ include "internetaakafhandeling.fullname" . }}-secrets
  labels:
    {{- include "internetaakafhandeling.labels" . | nindent 4 }}
type: Opaque
data:
  # Database connection
  ConnectionStrings__DefaultConnection: {{ include "internetaakafhandeling.databaseConnectionString" . | b64enc }}
  
  # API Keys
  OpenKlantApi__ApiKey: {{ .Values.apiConnections.openKlant.apiKey | b64enc }}
  ObjectApi__ApiKey: {{ .Values.apiConnections.object.apiKey | b64enc }}
  ZaakSysteem__Key: {{ .Values.apiConnections.zaakSysteem.key | b64enc }}
  
  # OIDC Secret
  {{- if .Values.web.oidc.clientSecret }}
  OIDC_CLIENT_SECRET: {{ .Values.web.oidc.clientSecret | b64enc }}
  {{- end }}
  
  # SMTP Password
  Email__SmtpSettings__Password: {{ .Values.poller.smtp.password | b64enc }}