{{- if .Values.web.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "internetaakafhandeling.web.fullname" . }}-config
  labels:
    {{- include "internetaakafhandeling.web.labels" . | nindent 4 }}
data:
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
  
  # API Connections
  OpenKlantApi__BaseUrl: {{ .Values.web.apiConnections.openKlant.baseUrl | quote }}
  ObjectApi__BaseUrl: {{ .Values.web.apiConnections.object.baseUrl | quote }}
  ZaakSysteem__BaseUrl: {{ .Values.web.apiConnections.zaakSysteem.baseUrl | quote }}
  ZaakSysteem__ClientId: {{ .Values.web.apiConnections.zaakSysteem.clientId | quote }}
  
  # OIDC Configuration
  {{- if .Values.web.oidc.authority }}
  OIDC_AUTHORITY: {{ .Values.web.oidc.authority }}
  OIDC_CLIENT_ID: {{ .Values.web.oidc.clientId }}
  OIDC_ITA_SYSTEM_ACCESS_ROLE: {{ .Values.web.oidc.itaSystemAccessRole }}
  OIDC_NAME_CLAIM_TYPE: {{ .Values.web.oidc.nameClaimType }}
  OIDC_ROLE_CLAIM_TYPE: {{ .Values.web.oidc.roleClaimType }}
  OIDC_ID_CLAIM_TYPE: {{ .Values.web.oidc.idClaimType }}
  {{- end }}
  
  # Resource configuration
  {{- if .Values.web.resources.logoUrl }}
  RESOURCES__LOGO_URL: {{ .Values.web.resources.logoUrl | toString | quote }}
  RESOURCES__FAVICON_URL: {{ .Values.web.resources.faviconUrl | toString | quote }}
  RESOURCES__DESIGN_TOKENS_URL: {{ .Values.web.resources.designTokensUrl | toString | quote }}
  RESOURCES__WEB_FONT_SOURCES: {{ join " " .Values.web.resources.webFontSources | quote }}
  {{- end }}
{{- end }}