apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "internetaakafhandeling.web.name" . }}-appsettings
  labels:
    {{- include "internetaakafhandeling.web.labels" . | nindent 4 }}
data:
  appsettings.json: |-
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "AllowedHosts": "*",
      "Setting1": "{{ .Values.web.appsettings.setting1 }}",
      "Setting2": "{{ .Values.web.appsettings.setting2 }}"
    }