apiVersion: v1
kind: Service
metadata:
  name: {{ include "internetaakafhandeling.web.name" . }}-svc
  labels:
    {{- include "internetaakafhandeling.web.labels" . | nindent 4 }}
spec:
  type: {{ .Values.web.service.type }}
  selector:
    {{- include "internetaakafhandeling.web.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: 8080