apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "internetaakafhandeling.web.name" . }}
  labels:
    {{- include "internetaakafhandeling.web.labels" . | nindent 4 }}
spec:
  replicas: 1 # we need to persist data protection keys before we can add more replicas. otherwise login with oidc breaks
  selector:
    matchLabels:
      {{- include "internetaakafhandeling.web.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "internetaakafhandeling.web.selectorLabels" . | nindent 8 }}
      annotations:
        # we include the checksum of the config and secrets in here.
        # the key of the annotations can be anything
        # by doing this, we make sure a re-deploy is triggered whenever any config / secret changes 
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
    spec:
      containers:
        - name: internetaakafhandeling-web
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          ports:
            - containerPort: 8080
              name: http
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          volumeMounts:
            - name: appsettings-volume
              mountPath: /app/appsettings.json
              subPath: appsettings.json
          envFrom:
            - configMapRef:
                name: {{ include "internetaakafhandeling.fullname" . }}-config
            - secretRef:
                name: {{ include "internetaakafhandeling.fullname" . }}-secrets
      volumes:
        - name: appsettings-volume
          configMap:
            name: {{ include "internetaakafhandeling.web.name" . }}-appsettings