image:
  repository: "ghcr.io/interne-taak-afhandeling/internetaakafhandeling.web"
  tag: "0.0.8-06ffa27"
  pullPolicy: IfNotPresent
config:
  oidc:
    authority: ""
    clientId: ""
    clientSecret: ""
    itaSystemAccessRole: ""
    nameClaimType: ""
    roleClaimType: ""
    idClaimType: ""
  resources:
    logoUrl: ""
    faviconUrl: ""
    designTokensUrl: ""
    webFontSources: []