image:
  repository: "ghcr.io/interne-taak-afhandeling/internetaakafhandeling.web"
  tag: "0.0.8-06ffa27"
  pullPolicy: IfNotPresent
appsettings:
  setting1: "helm value for Setting1"
  setting2: "helm value for Setting2"