{{- if .Values.certificates.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "internetaakafhandeling.fullname" . }}-cert
spec:
  secretName: {{ include "internetaakafhandeling.fullname" . }}-tls
  issuerRef:
    name: {{ .Values.certificates.issuerName }}
    kind: ClusterIssuer
  dnsNames:
    - {{ .Values.certificates.commonName }}
{{- end }}
