apiVersion: v1
kind: Secret
metadata:
  name: {{ include "internetaakafhandeling.fullname" . }}-shared-secret
type: Opaque
data:
  OpenKlantApi__ApiKey: {{ .Values.secrets.openKlantApiKey | b64enc }}
  ObjectApi__ApiKey: {{ .Values.secrets.objectApiKey | b64enc }}
  ConnectionStrings__DefaultConnection: {{ printf "Host=%s;Port=%s;Database=%s;Username=%s;Password=%s;" .Values.config.database.host .Values.config.database.port .Values.config.database.name .Values.config.database.username .Values.secrets.databasePassword | b64enc }}