apiVersion: v1
kind: Secret
metadata:
  name: {{ include "internetaakafhandeling.fullname" . }}-shared-secret
type: Opaque
data:
  OpenKlantApi__ApiKey: {{ .Values.secrets.openKlantApiKey | b64enc }}
  ObjectApi__ApiKey: {{ .Values.secrets.objectApiKey | b64enc }}
  ZaakSysteem__Key: {{ .Values.secrets.zaakSysteemKey | b64enc }}