schedule: "* * * * *"
image:
  repository: ghcr.io/interne-taak-afhandeling/internetaakafhandeling.poller
  tag: 0.0.1-546f239
  pullPolicy: Always
appsettings:
  PollerMessage: "testbericht uit helm Poller values"