apiVersion: v2
name: internetaakafhandeling
description: Helm chart for InterneTaakAfhandeling including Web API and Poller
type: application
version: 1.0.1
appVersion: 1.0.1
dependencies:
  - name: postgresql
    version: 12.5.6
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled