apiVersion: v2
name: internetaakafhandeling
description: Helm chart for InterneTaakAfhandeling including Web API and Poller
type: application
version: 0.2.0
appVersion: 0.2.0
dependencies:
  - name: postgresql
    version: 12.5.6
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled