apiVersion: v2
name: internetaakafhandeling
description: Helm chart for InterneTaakAfhandeling with independently deployable Web API and Poller components
type: application
version: 0.1.0
appVersion: 0.1.0
dependencies:
  - name: postgresql
    version: 12.5.6
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled