# Naming overrides - useful when used as subchart
nameOverride: ""
fullnameOverride: ""

# Global PostgreSQL configuration
postgresql:
  enabled: true
  image:
    repository: bitnamilegacy/postgresql
  auth:
    username: ""
    password: ""
    database: "interneTaakAfhandeling"
    postgresPassword: ""
  primary:
    persistence:
      enabled: true
      size: 8Gi
  metrics:
    enabled: false
    image:
      repository: bitnamilegacy/postgres-exporter
  volumePermissions:
    image:
      repository: bitnamilegacy/os-shell

# Ingress Configuration
ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  className: ""
  # -- ingress hosts
  hosts: []
  #  - host: ita.gemeente.nl
  #    paths:
  #      - path: /
  #        pathType: ImplementationSpecific
  tls: []
  #  - secretName: ita-tls
  #    hosts:
  #      - ita.gemeente.nl

# Database Configuration
database:
  # When postgresql.enabled=true, host is auto-set to {Release.Name}-postgresql
  # Specify this host only when postgresql.enabled=false
  host: ""
  port: "5432"
  name: "interneTaakAfhandeling"
  username: ""
  password: ""

# API Connections
apiConnections:
  openKlant:
    baseUrl: ""
    apiKey: ""
  object:
    baseUrl: ""
    apiKey: ""
  zaakSysteem:
    baseUrl: ""
    clientId: ""
    key: ""

logboek:
  # -- De url van het logboek objecttype in de objecttypen api. zie de objecttypen pagina in de documentatie for meer informatie
  type: ""
  # -- De versie van het logboek objecttype dat gebruikt wordt (hoogstwaarschijnlijk 1)
  typeVersion: 1

afdeling:
  # -- De url van het afdeling objecttype in de objecttypen api. zie de objecttypen pagina in de documentatie for meer informatie
  type: ""
  # -- De versie van het afdeling objecttype dat gebruikt wordt (hoogstwaarschijnlijk 1)
  typeVersion: 1

groep:
  # -- De url van het groep objecttype in de objecttypen api. zie de objecttypen pagina in de documentatie for meer informatie
  type: ""
  # -- De versie van het groep objecttype dat gebruikt wordt (hoogstwaarschijnlijk 1)
  typeVersion: 1

smtp:
  host: ""
  port: "25"
  username: ""
  password: ""
  fromEmail: ""
  enableSsl: "true"

# ITA Base URL for email deeplinks
# Example: https://itawebsite.nl
ita:
  baseUrl: ""

# Web Application Configuration
web:
  image:
    repository: "ghcr.io/interne-taak-afhandeling/internetaakafhandeling.web"
    tag: "latest"
    pullPolicy: Always
  
  service:
    type: ClusterIP
    port: 80
  
  oidc:
    authority: ""
    clientId: ""
    clientSecret: ""
    itaSystemAccessRole: ""
    functioneelBeheerderRole: ""
    nameClaimType: ""
    roleClaimType: ""
    objectregisterMedewerkerIdClaimType: ""
    emailClaimType: ""
  
  resources:
    logoUrl: ""
    faviconUrl: ""
    designTokensUrl: ""
    webFontSources: []
  
  appsettings:
    setting1: ""
    setting2: ""

# Poller Configuration
poller:
  schedule: "*/15 * * * *"
  
  image:
    repository: "ghcr.io/interne-taak-afhandeling/internetaakafhandeling.poller"
    tag: "latest"
    pullPolicy: Always
  
  notification:
    pollerMessage: "Poller uitgevoerd om:"
    hourThreshold: "-24"  
