// <auto-generated />
using System;
using InterneTaakAfhandeling.Poller.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InterneTaakAfhandeling.Poller.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250425135014_AddedLastInternetakenToegewezenOp")]
    partial class AddedLastInternetakenToegewezenOp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InterneTaakAfhandeling.Poller.Data.Entities.InternetakenNotifierState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("FailureCount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRunning")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LastInternetakenId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("LastInternetakenToegewezenOp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastRunAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastSuccessAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Remark")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("InternetakenNotifierStates");
                });
#pragma warning restore 612, 618
        }
    }
}
