name: Build, Push, and Deploy with Helm 

on:
  push:
    branches: [ main ]
  workflow_dispatch:    
    
permissions:
  contents: write
  
jobs:
  version-check:
      uses: ./.github/workflows/version-check.yml
      with:
        chart_path: "charts/internetaakafhandeling-umbrella-chart/Chart.yaml"

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: version-check
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate version tag
        id: version
        run: |
          VERSION=${{ needs.version-check.outputs.version }}
          echo "Version: $VERSION"
          if [ -z "$VERSION" ]; then
            VERSION="0.0.1"
          fi
          echo "Version: $VERSION"
          COMMIT=$(git rev-parse --short HEAD)
          IMAGE_TAG="${VERSION}-${COMMIT}"
          echo "::set-output name=image_tag::${IMAGE_TAG}"
          echo "::set-output name=version::${VERSION}"

      - name: Install yq
        run: |
          wget https://github.com/mikefarah/yq/releases/download/v4.34.1/yq_linux_amd64 -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq
      
      - name: Update chart values with new image tag
        run: |
          yq eval '.internetaakafhandeling-web.image.tag = "${{ steps.version.outputs.image_tag }}"' -i charts/internetaakafhandeling-umbrella-chart/values.yaml
          yq eval '.internetaakafhandeling-poller.image.tag = "${{ steps.version.outputs.image_tag }}"' -i charts/internetaakafhandeling-umbrella-chart/values.yaml

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGE_SECRET }}
          
      - name: Build and push internetaakafhandeling.web image
        run: |
          docker build -t ghcr.io/interne-taak-afhandeling/internetaakafhandeling.web:${{ steps.version.outputs.image_tag }} -f InterneTaakAfhandeling.Web.Server/Dockerfile .
          docker push ghcr.io/interne-taak-afhandeling/internetaakafhandeling.web:${{ steps.version.outputs.image_tag }}

      - name: Build and push internetaakafhandeling.poller image
        run: |
          docker build -t ghcr.io/interne-taak-afhandeling/internetaakafhandeling.poller:${{ steps.version.outputs.image_tag }} -f InterneTaakAfhandeling.Poller/Dockerfile .
          docker push ghcr.io/interne-taak-afhandeling/internetaakafhandeling.poller:${{ steps.version.outputs.image_tag }}
      - name: Set up Git user
        run: |
          git config --global user.email "pascal@icatt.nl"
          git config --global user.name "PascalIcatt"

      - name: Release Helm Charts with Chart Releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          skip_existing: false
          charts_dir: charts
        env:
          CR_TOKEN: ${{ secrets.PACKAGE_SECRET }}
          CR_OWNER: ${{ github.repository_owner }}
          CR_REPO: ${{ github.event.repository.name }}
          CR_FORCE: "true"
      
