name: Code quality checks
on:
  pull_request:
    branches: [main, "*.*.*"]

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Use Node.js lts
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
          cache-dependency-path: InterneTaakAfhandeling.Web.Client/package-lock.json
      - run: npm ci
        working-directory: InterneTaakAfhandeling.Web.Client
      - run: npm run lint:ci --if-present
        working-directory: InterneTaakAfhandeling.Web.Client
      - run: npm run format:ci --if-present
        working-directory: InterneTaakAfhandeling.Web.Client
